#! /bin/sh

export _JAVA_AWT_WM_NONREPARTENTING=1

xsetroot -cursor_name left_ptr

bspc monitor -d I II III IV V

bspc config border_width        1 
bspc config window_gap		8 

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a firefox desktop='^1'
bspc rule -a spotify desktop='^4'
#bspc rule -a mplayer2 state=floating
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off

#xsetrootst

#
# auto start applications
#
#/usr/bin/eww open powermenu &
pgrep -x sxhkd > /dev/null || sxhkd &
picom --config $HOME/.config/picom/picom.conf &
dunst --config $HOME/.config/dunst/dunstrc &
~/.config/polybar/launch.sh

#wallpaper
feh --bg-fill ~/Pictures/neogenises.png
